# Generated by Django 4.0.5 on 2022-07-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post_link_user_set_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='link_user_set',
            new_name='like_user_set',
        ),
    ]
